# Generated by Django 3.2.17 on 2023-03-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='product_name')),
                ('aspect_ratings', models.CharField(max_length=255, verbose_name='aspect_ratings')),
            ],
        ),
    ]
