# Generated by Django 3.2.17 on 2023-04-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20230422_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='product_type',
            field=models.CharField(default='default_value', max_length=255, verbose_name='product_type'),
        ),
    ]
