# Generated by Django 3.2.17 on 2023-04-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_reviews_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='delivery',
            field=models.CharField(default='default_value', max_length=255, verbose_name='delivery'),
        ),
    ]
