# Generated by Django 3.2.17 on 2023-04-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_books_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='fantasy',
            field=models.CharField(default='default_value', max_length=255, verbose_name='fantasy'),
        ),
        migrations.AddField(
            model_name='dvd',
            name='historical_accuracy',
            field=models.CharField(default='default_value', max_length=255, verbose_name='historical_accuracy'),
        ),
    ]
